logging:
  level:
    root: INFO
    sun.awt: INFO
    javax.swing: INFO
    java.awt: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.data.repository.config: WARN
    org.hibernate: INFO
    org.jboss.logging: INFO
    java.lang.Runtime: INFO
    org.hibernate.dialect.Dialect: WARN
    org.hibernate.jpa.internal.util.LogHelper: WARN

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/freya}
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-message: always
    path: /error

spring:
  main:
    allow-circular-references: false
    lazy-initialization: false
    allow-bean-definition-overriding: false

  application:
    name: Freya the Game
    version: 0.0.7
    author: KiraLis39
    company: Multiverse-39 Group, 2023

  profiles:
    group:
      dev: dev
      prod: prod
    default: dev
    active: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:./db/freya.db
    username: ${DB_LOGIN:freya}
    password: ${DB_PASSWORD:0358}
    driver-class-name: org.sqlite.JDBC
    hikari:
      poolName: Hikari
      auto-commit: true

      # Максимальное количество миллисекунд, в течение которых клиент (то есть вы) будет ожидать соединения из пула.
      #   Если это время превышено, а соединение не становится доступным, будет выдано исключение SQLException.
      #   Минимально допустимое время ожидания соединения составляет 250 мс. По умолчанию: 30000 (30 секунд)
      connection-timeout: 45000

      # Максимальное время, в течение которого соединению разрешено простаивать в пуле.
      #   Применяется если minimumIdle меньше maximumPoolSize. Неактивные соединения не будут удалены после того,
      #   как пул достигнет minimumIdle соединений. Независимо от того, будет ли соединение отключено как бездействующее
      #   или нет, максимальное отклонение составит +30 секунд, а среднее отклонение составит +15 секунд.
      #   Соединение никогда не будет отключено как бездействующее до истечения этого таймаута.
      #   Значение 0 означает, что простаивающие соединения никогда не удаляются из пула.
      #   Минимально допустимое значение — 10000 мс (10 секунд). По умолчанию: 600000 (10 минут).
      idle-timeout: 600000

      # Максимальный размер пула, включая как простаивающие, так и используемые соединения.
      #   По сути, это значение будет определять максимальное количество фактических подключений к базе данных.
      #   Разумное значение этого параметра лучше всего определяется вашей средой выполнения.
      #   Когда пул достигнет этого размера и не будет свободных соединений, вызовы getConnection()
      #   будут блокироваться на срок до connection-timeout, прежде чем истечет время ожидания.
      maximum-pool-size: 15

      # Максимальное время жизни соединения в пуле. Используемое соединение будет удалено только когда будет закрыто.
      #   Для каждого соединения применяется незначительное отрицательное затухание, чтобы избежать массового затухания в пуле.
      #   Должно быть на несколько секунд короче, чем ограничение времени подключения, установленное любой БД.
      max-lifetime: 900000

      # Как часто HikariCP будет пытаться поддерживать соединение, чтобы предотвратить
      #   его тайм-аут из-за базы данных или сетевой инфраструктуры. Это значение должно быть меньше max-lifetime:
      keepalive-time: 180000

  # liquibase:
  #   change-log: classpath:db/changelog/changelog.xml
  #   # drop-first: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        check_nullability: true
        jdbc:
          # Hibernate прозрачно отключает пакетную вставку на уровне JDBC, если вы используете генератор IDENTITY
          batch_size: 10
          batch_versioned_data: true
        order_updates: true
        connection:
          autocommit: true
          pool_size: 6
        # dialect: org.hibernate.community.dialect.SQLiteDialect
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
    # database-platform: org.hibernate.community.dialect.SQLiteDialect
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect

game:
  doubleBuffered: ${DOUBLE_BUFFERED_ENABLED:false}
  dataBaseRootDir: ${DB_ROOT_DIRECTORY:./db/}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    config-url: "${API_DOCS_MAIN_URI:${server.servlet.context-path:}}/v3/api-docs/swagger-config"
    url: "${API_DOCS_MAIN_URI:${server.servlet.context-path:}}/v3/api-docs"

#management:
#  endpoint:
#    health:
#      probes:
#        enabled: true
